/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

[scriptable, uuid(e3b2c4d6-7890-4abc-def1-234567890abc)]
interface nsICastVideoEncoder : nsISupports
{
    void init(in unsigned long width, in unsigned long height,
              in unsigned long bitrate, in unsigned long fps);

    Array<octet> encodeFrame(in Array<octet> rgbaData, in boolean forceKeyframe, in long long timestampMs);

    Array<octet> getHeader();

    void shutdown();

    void dumpTestWebM(in unsigned long frames);
};
